---
# tasks file for ansible-role-sjk/

- name: "Ensure SJK dest path exists"
  file:
    path: "{{ sjk_dest }}"
    state: directory
    owner: "{{ sjk_owner }}"
    group: "{{ sjk_group }}"
    mode: "u=rwX,g=rX,o=rX"

- name: "Ensure SJK binary exists"
  stat:
    path: "{{ sjk_dest }}/{{ __sjk_binary_name }}"
  register: sjk_binary_stat

- name: "Download SJK binary"
  maven_artifact:
    group_id: "{{ __sjk_group_id }}"
    artifact_id: "{{ __sjk_artifact_id }}"
    version: "{{ sjk_version }}"
    repository_url: "{{ sjk_repo_url | default(omit) }}"
    state: present
    username: "{{ sjk_repo_username | default(omit) }}"
    password: "{{ sjk_repo_password | default(omit) }}"
    timeout: "{{ __sjk_maven_artifact_timeout }}"
    dest: "{{ sjk_dest }}"
  when: not sjk_binary_stat.stat.exists

- name: "Ensure SJK binary ownership"
  file:
    path: "{{ sjk_dest }}/{{ __sjk_binary_name }}"
    owner: "{{ sjk_owner }}"
    group: "{{ sjk_group }}"
    mode: "{{ sjk_chmod }}"

- name: "Ensure system required packages are installed"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "python-lxml"
